# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-01 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pic',
            new_name='picture',
        ),
    ]
